### ISSUE TITLE
Json and Csv export seems to be incorrect

### ISSUE THREAD

**Issue by stefankeil** [funkeinteraktiv/geo-data-merger#1]
Given: Two json files via copy/paste. 
The output merged json and csv seems to be broken.

![screenshot 2018-12-18 at 11 34 41](https://user-images.githubusercontent.com/64068/50148705-79f7d080-02b9-11e9-985d-346675af7d93.png)

**Comment by moklick** [comment]
In order to merge geojson files the features need properties. We don't use the geometries to merge the files, but the properties.

**Comment by stefankeil** [comment]
Ah ok, thanks 👍
