### ISSUE TITLE
Export geo files to KML

### ISSUE THREAD

**Issue by tursics** [funkeinteraktiv/geo-data-merger#4]
Der Claus aus Moers möchte gerne für Wolfgang Ksoll seine Geodaten in KML exportieren lassen wollen gerne. Das ist ihm wichtig, um Daten in Google Maps zu befüllen.

**Comment by moklick** [comment]
Hey Thomas,

am besten nutzt ihr dafür ein Online-Tool wie zB. [geojson.io](http://geojson.io).
Wir haben keine Converter Features geplant.

**Comment by tursics** [comment]
Alles klar. Danke. War nur ne Idee, weil geojson.io mit großen Daten einfriert.
